FROM mhart/alpine-node:8 as APP_NAME-builder
LABEL maintainer=MAINTAINER

# RUN apt-get update && apt-get install libssl-dev -y
WORKDIR /app
COPY ./dummy/package* /app/
COPY ./dummy/yarn* /app/

RUN yarn install

FROM mhart/alpine-node:8
LABEL maintainer=MAINTAINER

RUN mkdir -p /app
WORKDIR /app

COPY --from=APP_NAME-builder /app/node_modules /app/node_modules
COPY . /app

EXPOSE 3000
CMD [ "npm", "start" ]
